# -*- coding: utf-8 -*-
"""area_rectangulo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNKyUzFEul8gxIABKs4TuwPeGfTZy6_K
"""

def calcular_area(base, altura):
    return base * altura

base = float(input("ingrese la base del rectangulo:"))
altura = float(input("ingrese la altura del rectangulo:"))

area =calcular_area(base, altura)
print("el area del rectangulo es:", area)